#> DATASET: neighborhoods (bairros)
#> Source: IBGE
#>   2010: derived from census tracts (pipeline dependency: censustract_clean)
#>   2022: https://geoftp.ibge.gov.br/.../censo_2022/bairros/gpkg/BR/BR_bairros_CD2022.gpkg
#> Metadata:
# Titulo: Bairros
# Frequencia de atualizacao: Censal (2010, 2022)
# Forma de apresentacao: GPKG (2022) / Census tract dissolve (2010)
# Linguagem: Pt-BR
# Character set: UTF-8
# Informacao do Sistema de Referencia: SIRGAS 2000

# Download the data  -----------------------------------------------------------
# censustract_files: vector of parquet paths from censustract_clean target
# This creates an explicit DAG dependency: census_tract must run before neighborhood
# download_neighborhoods <- function(year, censustract_files = NULL) {
# 
#   if (year == 2010) {
#     ## 2010: read census tract parquets from pipeline (generated by census_tract target)
#     ct_files <- censustract_files[grepl("census_tract/2010", censustract_files)]
#     ct_files <- ct_files[!grepl("simplified", ct_files)]
# 
#     if (length(ct_files) == 0) {
#       stop("census_tract 2010 parquets not found. Run censustract_clean first.")
#     }
# 
#     message(sprintf("[neighborhood 2010] Lendo %d parquets de census_tract...", length(ct_files)))
#     raw <- read_geoparquet(ct_files)
#     message(sprintf("[neighborhood 2010] Total: %d rows", nrow(raw)))
# 
#   }
# 
#   if (year == 2022) {
#     ## 2022: direct GPKG from IBGE (separate file, not from census_tract)
#     ftp_link <- "https://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_de_setores_censitarios__divisoes_intramunicipais/censo_2022/bairros/gpkg/BR/BR_bairros_CD2022.gpkg"
# 
#     message("[neighborhood 2022] Baixando GPKG do IBGE...")
#     tmp <- tempfile(fileext = ".gpkg")
#     httr::GET(url = ftp_link, httr::progress(),
#               httr::write_disk(path = tmp, overwrite = TRUE),
#               httr::timeout(600))
# 
#     raw <- sf::st_read(tmp, quiet = TRUE)
#     message(sprintf("[neighborhood 2022] Total: %d rows", nrow(raw)))
#   }
# 
#   raw$year <- year
#   return(raw)
#   
#   
# }

# Clean the data  --------------------------------------------------------------

# censustract_files <- tar_read(censustract_clean)

clean_neighborhoods <- function(censustract_files) {

  # 2022 tem os dados prontos de bairros
  # https://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_de_setores_censitarios__divisoes_intramunicipais/censo_2022/bairros/gpkg/BR/BR_bairros_CD2022.gpkg
  
  dir_root <- paste0("./data/neighborhood/")
  dir.create(dir_root, recursive = T, showWarnings = FALSE)
  
  # read census tract parquets from pipeline (generated by census_tract target)
  
  # drop simplified geometries
  censustract_files <- censustract_files[!grepl("simplified", censustract_files)]
  
  # creates neighborhoods by merging census tracts and saves files

  for (i in censustract_files){  # i = censustract_files[1]
  
    temp <- arrow::open_dataset(i) |> 
      dplyr::filter(!is.na(code_neighborhood)) |> 
      sf::st_as_sf()
    
    ## 0. Create folder to save clean data
    yyyy <- temp$year[1]
    dir_clean <- paste0(dir_root, yyyy)
    dir.create(dir_clean, recursive = T, showWarnings = FALSE)
    message(yyyy)
  
    
    # fix code_neighborhood
    # issue https://github.com/ipeaGIT/geobr/issues/182
    # as.numeric() pra respeitar a regra code_* = numeric (CLAUDE.md). Validado
    # empiricamente em 2010+2022: 0 NAs criados, 10 digitos, max 5.218.300.013
    # (bem abaixo do limite double seguro 9.007e15).
    temp <- temp |>
      mutate(code_neighborhood = as.numeric(paste0(
        code_muni,
        substr(code_neighborhood, nchar(code_neighborhood) - 2, nchar(code_neighborhood))
        ))
      )
    

    
    # dissolve polygons  --------------------------------------------------
    # c) long but complete dissolve function
  
    all_neighborhoods <- dissolve_polygons_no_split(
      mysf = temp,
      group_column = "code_neighborhood"
    )

    # select columns and remove duplicates
    temp_sf <- all_neighborhoods |> 
      dplyr::select(code_muni, name_muni, code_neighborhood, 
                    name_neighborhood, code_district, name_district, 
                    code_subdistrict, name_subdistrict, code_state, 
                    abbrev_state, name_state, code_region, name_region, 
                    year ) |> 
      unique()  

    # sort by key columns
    temp_sf <- temp_sf |> 
      dplyr::arrange(code_state, code_muni, code_neighborhood)

    
  ## Harmonize -----------------------------------------------------------------

  # temp_sf <- harmonize_geobr(
  #   temp_sf        = temp_sf,
  #   year           = year,
  #   add_state      = F,
  #   # state_column   = "code_state",
  #   add_region     = F,
  #   # region_column  = "code_state",
  #   add_snake_case = F,
  #   # snake_colname  = "name_neighborhood",
  #   projection_fix = TRUE,
  #   encoding_utf8  = TRUE,
  #   topology_fix   = TRUE,
  #   remove_z_dimension = TRUE,
  #   use_multipolygon   = TRUE
  # )

  # 
  # ## Column order --------------------------------------------------------------
  # 
  # temp_sf <- temp_sf |>
  #   dplyr::select(
  #     code_neighborhood, name_neighborhood,
  #     code_district, name_district,
  #     code_subdistrict, name_subdistrict,
  #     code_muni, name_muni,
  #     code_state, abbrev_state, name_state,
  #     code_region, name_region,
  #     year, geometry
  #   )

  ## Validate ------------------------------------------------------------------

  # stopifnot(all(sf::st_geometry_type(temp_sf) == "MULTIPOLYGON"))

  ## Lighter version -----------------------------------------------------------

  temp_sf_simplified <- simplify_temp_sf(temp_sf, tolerance = 10)

  ## Save datasets -------------------------------------------------------------

  write_geobr_parquet(
    temp_sf,
    paste0(dir_clean, "/neighborhoods_", yyyy, ".parquet"))

  write_geobr_parquet(
    temp_sf_simplified,
    paste0(dir_clean, "/neighborhoods_", yyyy, "_simplified.parquet"))

  }
  
  files <- list.files(dir_clean, pattern = "[.]parquet$",
                      full.names = TRUE, recursive = TRUE)
  return(files)
}



# Helper: Clean 2022 data (direct GPKG from IBGE)

clean_neighborhoods_2022 <- function(raw) {

  temp_sf <- raw |>
    dplyr::select(
      code_neighborhood  = CD_BAIRRO,
      name_neighborhood  = NM_BAIRRO,
      code_district      = CD_DIST,
      name_district      = NM_DIST,
      code_subdistrict   = CD_SUBDIST,
      name_subdistrict   = NM_SUBDIST,
      code_muni          = CD_MUN,
      name_muni          = NM_MUN,
      code_state         = CD_UF
    )

  # Remove lakes (administrative areas, not real neighborhoods)
  temp_sf <- dplyr::filter(temp_sf,
                           code_muni != 430000100000000,
                           code_muni != 430000200000000)


  return(temp_sf)
}


# ==============================================================================
# Helper: Clean 2010 data (dissolve from census tracts)
# 3-part approach: neighborhood > subdistrict > district
# ==============================================================================
clean_neighborhoods_2010 <- function(tracts) {

  # Ensure UTF-8 and MULTIPOLYGON
  tracts <- use_encoding_utf8(tracts)
  tracts <- sf::st_cast(tracts, "MULTIPOLYGON")

  ## Part 1: municipalities with neighborhood info ----------------------------
  nei <- dplyr::filter(tracts, !is.na(name_neighborhood))
  all_muni_p1 <- unique(nei$code_muni)

  part1 <- dissolve_by_group(nei, "code_neighborhood")

  # Recover metadata
  meta1 <- sf::st_drop_geometry(nei) |>
    dplyr::select(code_muni, name_muni, name_neighborhood, code_neighborhood,
                  code_subdistrict, name_subdistrict, code_district, name_district) |>
    dplyr::distinct()
  part1 <- dplyr::left_join(part1, meta1, by = "code_neighborhood")

  # Remove municipalities with single observation (covers whole municipality)
  part1 <- part1 |>
    dplyr::group_by(code_muni) |>
    dplyr::filter(dplyr::n() > 1) |>
    dplyr::ungroup()

  ## Part 2: municipalities with subdistrict info only ------------------------
  sub <- dplyr::filter(tracts, is.na(name_neighborhood), !is.na(name_subdistrict))
  sub <- dplyr::filter(sub, !(code_muni %in% all_muni_p1))
  all_muni_p2 <- unique(sub$code_muni)

  part2 <- dissolve_by_group(sub, "code_subdistrict")

  meta2 <- sf::st_drop_geometry(sub) |>
    dplyr::select(code_muni, name_muni, code_subdistrict, name_subdistrict,
                  code_district, name_district) |>
    dplyr::distinct()
  part2 <- dplyr::left_join(part2, meta2, by = "code_subdistrict")
  part2$name_neighborhood <- NA_character_
  part2$code_neighborhood <- NA_real_

  # Remove municipalities with few observations
  part2 <- part2 |>
    dplyr::group_by(code_muni) |>
    dplyr::filter(dplyr::n() > 5) |>
    dplyr::ungroup()

  ## Part 3: municipalities with district info only ---------------------------
  dist <- dplyr::filter(tracts, is.na(name_neighborhood), is.na(name_subdistrict),
                         !is.na(name_district))
  dist <- dplyr::filter(dist, !(code_muni %in% all_muni_p1))
  dist <- dplyr::filter(dist, !(code_muni %in% all_muni_p2))

  part3 <- dissolve_by_group(dist, "code_district")

  meta3 <- sf::st_drop_geometry(dist) |>
    dplyr::select(code_muni, name_muni, code_district, name_district) |>
    dplyr::distinct()
  part3 <- dplyr::left_join(part3, meta3, by = "code_district")
  part3$name_neighborhood <- NA_character_
  part3$code_neighborhood <- NA_real_
  part3$code_subdistrict  <- NA_real_
  part3$name_subdistrict  <- NA_character_

  # Remove municipalities with few observations
  part3 <- part3 |>
    dplyr::group_by(code_muni) |>
    dplyr::filter(dplyr::n() > 15) |>
    dplyr::ungroup()

  ## Union all parts -----------------------------------------------------------
  cols <- c("code_neighborhood", "name_neighborhood",
            "code_district", "name_district",
            "code_subdistrict", "name_subdistrict",
            "code_muni", "name_muni")

  part1 <- dplyr::select(part1, dplyr::all_of(cols))
  part2 <- dplyr::select(part2, dplyr::all_of(cols))
  part3 <- dplyr::select(part3, dplyr::all_of(cols))

  temp_sf <- rbind(part1, part2, part3)

  # Final filter: remove municipalities with single observation
  temp_sf <- temp_sf |>
    dplyr::group_by(code_muni) |>
    dplyr::filter(dplyr::n() > 1) |>
    dplyr::ungroup()

  # Derive code_state from code_muni
  temp_sf$code_state <- substr(as.character(temp_sf$code_muni), 1, 2) |> as.numeric()

  return(temp_sf)
}


# ==============================================================================
# Helper: Dissolve polygons by group column (for 2010 census tract approach)
# Uses dissolve_polygons() from support_harmonize_geobr.R per municipality
# ==============================================================================
dissolve_by_group <- function(sf_data, group_column) {
  all_munis <- unique(sf_data$code_muni)

  result_list <- pbapply::pblapply(all_munis, function(m) {
    tryCatch({
      dissolve_polygons(
        mysf = dplyr::filter(sf_data, code_muni == m),
        group_column = group_column
      )
    }, error = function(e) {
      warning(paste("dissolve_polygons failed for muni", m, ":", conditionMessage(e)))
      NULL
    })
  })

  result_list <- Filter(Negate(is.null), result_list)
  do.call(rbind, result_list)
}
